
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Gadgeteer Designer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Gadgeteer;
using GTM = Gadgeteer.Modules;

namespace TestSpiderApp
{
    public partial class Program : Gadgeteer.Program
    {
        // GTM.Module defintions
		Gadgeteer.Modules.GHIElectronics.Button button;
		Gadgeteer.Modules.GHIElectronics.UsbClientDP usbClient;
		Gadgeteer.Modules.GHIElectronics.MulticolorLed led;
		Gadgeteer.Modules.Seeed.Accelerometer accelerometer;
		Gadgeteer.Modules.GHIElectronics.Ethernet_J11D ethernet;

		public static void Main()
        {
			//Important to initialize the Mainboard first
            Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();			

            Program program = new Program();
			program.InitializeModules();
            program.ProgramStarted();
            program.Run(); // Starts Dispatcher
        }

        private void InitializeModules()
        {   
			// Initialize GTM.Modules and event handlers here.		
			usbClient = new GTM.GHIElectronics.UsbClientDP(1);
		
			accelerometer = new GTM.Seeed.Accelerometer(3);
		
			led = new GTM.GHIElectronics.MulticolorLed(6);
		
			ethernet = new GTM.GHIElectronics.Ethernet_J11D(7);
		
			button = new GTM.GHIElectronics.Button(11);

        }
    }
}
